name: venice_core
description: This project aims at providing a unified abstract interface to exchange data between devices using different technologies.

publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  protobuf: ^3.1.0
  buffer: ^1.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
